services:
  azurite:
    build:
      context: azurite
    container_name: blobfs-azurite
    ports:
      - "127.0.0.1:${AZURITE_BLOB_PORT:-10000}:10000"
    volumes:
      - blobfs-azurite:/data

volumes:
  blobfs-azurite:
